import logging
from pydantic import BaseModel, Field, field_validator
from typing import List, Dict, Any

logger = logging.getLogger(__name__)

_URL_PATTERN = r"https?://[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(:\d+)?(/[^\s]*)?"


class TrendPayload(BaseModel):
    """Data contract generated by the Trend Investigator agent."""
    __version__ = "1.0"
    trend_name: str = Field(..., description="The unified, specific name of the identified industry shift.")
    momentum_score: float = Field(..., description="Calculated trend significance scale from 0.0 to 1.0.")
    extracted_metrics: Dict[str, Any] = Field(..., description="Key performance indicators, data numbers, or developer usage metrics.")
    verified_sources: List[str] = Field(..., description="Explicit, tracked source links where information was extracted.")

    @field_validator("verified_sources")
    @classmethod
    def _sanitize_urls(cls, v: List[str]) -> List[str]:
        import re
        valid: list[str] = []
        pattern = re.compile(_URL_PATTERN)
        for item in v:
            item = item.strip()
            if pattern.fullmatch(item):
                valid.append(item)
            else:
                found = [m.group(0) for m in pattern.finditer(item)]
                if found:
                    logger.warning("Extracted URLs from non-URL source text: %r -> %s", item, found)
                    valid.extend(found)
                else:
                    logger.warning("Filtered out invalid source (no URL found): %r", item)
        if not valid:
            valid.append("https://placeholder.sanitized-source")
        return valid

class RiskPayload(BaseModel):
    """Data contract generated by the Risk Analyst agent evaluating the TrendPayload."""
    __version__ = "1.0"
    is_safe: bool = Field(..., description="Absolute flag indicating if the trend details pass enterprise compliance.")
    risk_score: float = Field(..., description="Risk evaluation penalty from 0.0 (no risk) to 1.0 (malicious/highly inaccurate).")
    flagged_keywords: List[str] = Field(default_factory=list, description="Specific terms or concepts that triggered a compliance flag.")
    required_revisions: List[str] = Field(default_factory=list, description="Actionable modification guidelines required to clear the payload.")

class ContentPayload(BaseModel):
    """Final output data block delivered by the Copywriter agent."""
    __version__ = "1.0"
    headline: str = Field(..., description="Engaging, conversion-driven headline designed for B2B channels.")
    body_content: str = Field(..., description="The complete, production-grade text body synthesized from grounded data vectors.")
    metadata_tags: List[str] = Field(..., description="SEO and cross-channel indexing tags matched to the target trend.")
