from pydantic import BaseModel, Field, field_validator
from typing import List, Dict, Any

class TrendPayload(BaseModel):
    """Data contract generated by the Trend Investigator agent."""
    trend_name: str = Field(..., description="The unified, specific name of the identified industry shift.")
    momentum_score: float = Field(..., description="Calculated trend significance scale from 0.0 to 1.0.")
    extracted_metrics: Dict[str, Any] = Field(..., description="Key performance indicators, data numbers, or developer usage metrics.")
    verified_sources: List[str] = Field(..., description="Explicit, tracked source links where information was extracted.")

    @field_validator("verified_sources")
    @classmethod
    def _validate_urls(cls, v: List[str]) -> List[str]:
        import re
        pattern = re.compile(
            r"^https?://"  
            r"("
            r"localhost|"
            r"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}|"
            r"[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
            r")"
            r"(:\d+)?"
            r"(/[^\s]*)?$"
        )
        for item in v:
            if not pattern.match(item):
                raise ValueError(
                    f"'{item}' is not a valid URL. "
                    f"URLs must start with http:// or https:// and have a valid host."
                )
        return v

class RiskPayload(BaseModel):
    """Data contract generated by the Risk Analyst agent evaluating the TrendPayload."""
    is_safe: bool = Field(..., description="Absolute flag indicating if the trend details pass enterprise compliance.")
    risk_score: float = Field(..., description="Risk evaluation penalty from 0.0 (no risk) to 1.0 (malicious/highly inaccurate).")
    flagged_keywords: List[str] = Field(default_factory=list, description="Specific terms or concepts that triggered a compliance flag.")
    required_revisions: List[str] = Field(default_factory=list, description="Actionable modification guidelines required to clear the payload.")

class ContentPayload(BaseModel):
    """Final output data block delivered by the Copywriter agent."""
    headline: str = Field(..., description="Engaging, conversion-driven headline designed for B2B channels.")
    body_content: str = Field(..., description="The complete, production-grade text body synthesized from grounded data vectors.")
    metadata_tags: List[str] = Field(..., description="SEO and cross-channel indexing tags matched to the target trend.")
